name: example
version: 0.1.0.0

dependencies:
  - base >= 4.7 && < 5
  - katip
  - katip-wai
  - servant
  - servant-server
  - wai
  - warp
  - unliftio-core

executables:
  example-exe:
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
