name: "Build Haskell - Cabal"
description: "Build haskell project with cabal"
inputs:
  cabal-version:
    description: "Version of cabal to use"
    required: false
    default: "3.6.2"
  ghc-version:
    description: "Version of ghc to use"
    required: false
    default: "8.10.7"
runs:
  using: "composite"
  steps:
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell and Cabal
      with:
        ghc-version: ${{ inputs.ghc-version }}
        cabal-version: ${{ inputs.cabal-version }}

    - name: Freeze
      shell: bash
      run: |
        cabal freeze

    - uses: actions/cache@v2.1.3
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

    - name: Install dependencies
      shell: bash
      run: |
        cabal build all --only-dependencies

    - name: Build
      shell: bash
      run: |
        cabal build all

    - name: Test
      shell: bash
      run: |
        cabal test all
