name: katip-wai
version: 0.1.0.0
github: "Disco-Dave/katip-wai"
license: BSD3
author: "David Burkett"
maintainer: "David Burkett"
copyright: "2021 David Burkett"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
synopsis: WAI middleware for logging request and response info through katip.
category: Web, Logging

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: WAI middleware for logging request and response info through katip. Please see the README on GitHub at <https://github.com/Disco-Dave/katip-wai#readme>

ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-prepositive-qualified-module
  - -Wno-missing-safe-haskell-mode
  - -Wno-missing-deriving-strategies

dependencies:
  - base >= 4.7
  - aeson >= 0.6
  - bytestring >= 0.9
  - clock >= 0.8
  - http-types >= 0.12
  - katip >= 0.8
  - network >= 3.0
  - text >= 0.11
  - uuid >= 1.3
  - wai >= 3.0

library:
  source-dirs: src

tests:
  katip-wai-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wno-unused-packages
    build-tools:
      - hspec-discover:hspec-discover == 2.*
    dependencies:
      - katip-wai
      - async >= 2.0
      - containers >= 0.6
      - hspec >= 2.7
      - http-client >= 0.6
      - stm >= 2.5
      - warp >= 3.3
