name: "Build Haskell - Stack"
description: "Build haskell project with stack"
inputs:
  stack-version:
    description: "Version of stack to use"
    required: false
    default: "2.7.3"
  resolver:
    description: "Resolver to use from stackage"
    required: false
    default: "lts-19.7"
runs:
  using: "composite"
  steps:
    - uses: haskell/actions/setup@v1
      id: setup-haskell-stack
      name: Setup Haskell and Stack
      with:
        stack-version: ${{ inputs.stack-version }}
        enable-stack: true
        stack-no-global: true

    - uses: actions/cache@v2.1.3
      name: Cache ~/.stack
      with:
        path: ${{ steps.setup-haskell-stack.outputs.stack-root }}
        key: ${{ runner.os }}-${{ matrix.resolver }}-stack

    - name: Setup stack
      shell: bash
      run: |
        stack setup --resolver "${{ matrix.resolver }}"

    - name: Install dependencies
      shell: bash
      run: |
        stack build --resolver "${{ matrix.resolver }}"  --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

    - name: Build
      shell: bash
      run: |
        stack build --resolver "${{ matrix.resolver }}" --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      shell: bash
      run: |
        stack test --resolver "${{ matrix.resolver }}"
