imame: "Build Haskell - Stack"
description: "Build haskell project with stack"
inputs:
  stack-version:
    description: "Version of stack to use"
    required: false
    default: "2.7.3"
  ghc-version:
    description: "Version of ghc to use"
    required: false
    default: "8.10.7"
runs:
  using: "composite"
  steps:
    - uses: haskell/actions/setup@v1
      id: setup-haskell-stack
      name: Setup Haskell and Stack
      with:
        ghc-version: ${{ inputs.ghc-version }}
        stack-version: ${{ inputs.stack-version }}
        enable-stack: true

    - uses: actions/cache@v2.1.3
      name: Cache ~/.stack
      with:
        path: ${{ steps.setup-haskell-stack.outputs.stack-root }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Install dependencies
      shell: bash
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

    - name: Build
      shell: bash
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      shell: bash
      run: |
        stack test --system-ghc
