name: "ci"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cabal:
    name: ${{ matrix.os }} / cabal ${{ matrix.cabal }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        cabal: ["3.6"]
        ghc:
          - "8.8.4"
          - "8.10.7"
          - "9.0.1"
          - "9.2.1"
    steps:
      - uses: actions/checkout@v2

      - name: Fix cabal project for 9.2.1
        if: ${{ matrix.ghc == '9.2.1' }}
        run: |
          cp cabal.project cabal.project.backup 
          cat cabal.project.backup ghc-9.2.1.cabal.project > cabal.project 

      - uses: "./.github/actions/cabal-build"
        name: Build
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

  stack:
    name: ${{ matrix.os }} / stack ${{ matrix.stack }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        stack: ["2.7.3"]
        ghc: ["8.10.7"]
    steps:
      - uses: actions/checkout@v2

      - uses: "./.github/actions/stack-build"
        name: Build
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

  upload:
    name: "Publish to Hackage"
    if: startsWith( github.ref, 'refs/tags/releases/')
    needs:
      - cabal
      - stack
    uses: Disco-Dave/katip-wai/.github/workflows/upload.yaml@main
