name: "ci"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cabal:
    name: ${{ matrix.os }} / cabal ${{ matrix.cabal }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        cabal: ["3.6"]
        ghc:
          - "8.8.4"
          - "8.10.7"
          - "9.0.1"
          - "9.2.1"
    steps:
      - uses: actions/checkout@v2

      - uses: "./.github/actions/cabal-build"
        name: Build
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

  stack:
    name: ${{ matrix.os }} / stack ${{ matrix.stack }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        stack: ["2.7.3"]
        ghc: ["8.10.7"]
    steps:
      - uses: actions/checkout@v2

      - name: Fix cabal project
        if: ${{ matrix.ghc == "9.2.1" }}
        run: |
          cat cabal.project ghc-9.2.1.cabal.project > cabal.project

      - uses: "./.github/actions/stack-build"
        name: Build
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}
