name: "ci"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: 
      - created
      - published
      - released

jobs:
  cabal:
    name: ${{ matrix.os }} / cabal ${{ matrix.cabal }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        cabal: ["3.6"]
        ghc:
          - "8.8.4"
          - "8.10.7"
          - "9.0.1"
          - "9.2.1"
    steps:
      - uses: actions/checkout@v2

      - name: Fix cabal project for 9.2.1
        if: ${{ matrix.ghc == '9.2.1' }}
        run: |
          cp cabal.project cabal.project.backup 
          cat cabal.project.backup ghc-9.2.1.cabal.project > cabal.project 

      - uses: "./.github/actions/cabal-build"
        name: Build
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

  stack:
    name: ${{ matrix.os }} / stack ${{ matrix.stack }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        stack: ["2.7.3"]
        ghc: ["8.10.7"]
    steps:
      - uses: actions/checkout@v2

      - uses: "./.github/actions/stack-build"
        name: Build
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

  upload:
    name: "Publish to Hackage"
    runs-on: "ubuntu-latest"
    if: github.event_name == 'release'
    needs:
      - cabal
      - stack
    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        id: setup-haskell-cabal
        name: Setup Haskell and Cabal
        with:
          ghc-version: "8.10.7"
          cabal-version: "3.6"

      - name: Freeze
        run: |
          cabal freeze

      - uses: actions/cache@v2.1.3
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: Linux-8.10.7-${{ hashFiles('cabal.project.freeze') }}

      - name: "Bundle the package"
        run: |
          cabal sdist --builddir ./hackage-dist

      - name: "Bundle the documentation"
        run: |
          cabal haddock --builddir ./hackage-dist --haddock-for-hackage --haddock-options=--hyperlinked-source

      - name: "Upload package to Hackage"
        env:
          HACKAGE_USER: ${{ secrets.HACKAGE_USER }}
          HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
        run: |
          cabal upload -u $HACKAGE_USER -p $HACKAGE_PASSWORD ./hackage-dist/sdist/*.tar.gz 

      - name: "Upload docs to Hackage"
        env:
          HACKAGE_USER: ${{ secrets.HACKAGE_USER }}
          HACKAGE_PASSWORD: ${{ secrets.HACKAGE_PASSWORD }}
        run: |
          cabal upload -u $HACKAGE_USER -p $HACKAGE_PASSWORD -d ./hackage-dist/*-docs.tar.gz 
